export type CommitteeFeed = "un-geneva" | "un-news" | "who" | "india";

export type CommitteeProfile = {
  code: string;
  name: string;
  family: string;
  mandate: string;
  authority: string;
  focus: string[];
  keywords: string[];
  officialUrl: string;
  updatesUrl: string;
  accent: string;
  logo: string;
  logoAlt: string;
  feedGroups: CommitteeFeed[];
  simulation?: boolean;
};

export const COMMITTEES: CommitteeProfile[] = [
  { code: "UNHRC", name: "United Nations Human Rights Council", family: "Human rights", mandate: "Promotes and protects human rights worldwide, addresses violations, and makes recommendations through resolutions, reviews and special procedures.", authority: "The Council can create fact-finding mechanisms, appoint independent experts, conduct the Universal Periodic Review and convene special sessions. It does not impose criminal sentences or deploy forces.", focus: ["Universal Periodic Review", "Special procedures", "Civil and political rights"], keywords: ["human rights", "rights council", "unhrc", "ohchr"], officialUrl: "https://www.ohchr.org/en/hr-bodies/hrc/about-council", updatesUrl: "https://www.ohchr.org/en/hr-bodies/hrc/news", accent: "#82b7d8", logo: "/committee-logos/ohchr.svg", logoAlt: "United Nations Human Rights emblem", feedGroups: ["un-geneva", "un-news"] },
  { code: "UNSC", name: "United Nations Security Council", family: "Peace and security", mandate: "Carries primary responsibility for maintaining international peace and security under the United Nations Charter.", authority: "The Council may establish peace operations, impose sanctions, investigate disputes and, under the Charter, authorise collective action. Five permanent members hold veto power on substantive decisions.", focus: ["Conflict prevention", "Peace operations", "Sanctions and mandates"], keywords: ["security council", "unsc", "peacekeeping", "ceasefire", "sanctions"], officialUrl: "https://main.un.org/securitycouncil/en/content/what-security-council", updatesUrl: "https://main.un.org/securitycouncil/en", accent: "#d4b56d", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "DISEC", name: "Disarmament and International Security Committee", family: "UN General Assembly First Committee", mandate: "Examines disarmament, global challenges and threats to peace that affect the international community.", authority: "DISEC develops General Assembly recommendations and norms through multilateral debate. Its resolutions are generally recommendatory rather than legally binding.", focus: ["Weapons governance", "Outer space security", "Confidence-building measures"], keywords: ["disarmament", "first committee", "weapons", "arms control", "nuclear"], officialUrl: "https://www.un.org/en/ga/first/", updatesUrl: "https://www.un.org/en/ga/first/", accent: "#9ba8cf", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "UNGA", name: "United Nations General Assembly", family: "Global deliberation", mandate: "Provides all United Nations Member States with an equal forum to deliberate on international issues covered by the Charter.", authority: "The General Assembly approves the UN budget, elects members to UN organs and adopts recommendations. Most resolutions are not legally binding, though they carry political and normative weight.", focus: ["International cooperation", "UN budget and elections", "Global norms"], keywords: ["general assembly", "unga", "member states", "general debate"], officialUrl: "https://www.un.org/en/ga/about/", updatesUrl: "https://www.un.org/en/ga/", accent: "#76a9d3", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "SOCHUM", name: "Social, Humanitarian and Cultural Committee", family: "UN General Assembly Third Committee", mandate: "Considers social, humanitarian and human-rights questions affecting people around the world.", authority: "SOCHUM negotiates and recommends General Assembly resolutions on human rights, social development, crime prevention, refugees, children and related humanitarian questions.", focus: ["Human rights", "Refugees and displacement", "Social development"], keywords: ["third committee", "social humanitarian", "refugees", "human rights", "social development"], officialUrl: "https://www.un.org/en/ga/third/", updatesUrl: "https://www.un.org/en/ga/third/", accent: "#c58caa", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "WHO", name: "World Health Assembly", family: "Global health", mandate: "Sets the policies of the World Health Organization and brings member states together to decide global health priorities.", authority: "The Assembly appoints the Director-General, supervises financial policy and adopts conventions, regulations and recommendations within the WHO Constitution.", focus: ["Health emergencies", "Universal health coverage", "Antimicrobial resistance"], keywords: ["world health", "who", "health assembly", "public health", "health emergency"], officialUrl: "https://www.who.int/about/governance/world-health-assembly", updatesUrl: "https://www.who.int/news-room", accent: "#51a8cf", logo: "/committee-logos/who.svg", logoAlt: "World Health Organization logo", feedGroups: ["who", "un-news"] },
  { code: "UNEP", name: "United Nations Environment Programme", family: "Environment", mandate: "Provides leadership and encourages partnership in caring for the environment, helping nations improve quality of life without compromising future generations.", authority: "UNEP convenes states, produces authoritative science, supports environmental agreements and coordinates action; it relies on cooperation rather than enforcement powers.", focus: ["Climate action", "Nature and biodiversity", "Pollution and waste"], keywords: ["environment", "climate", "biodiversity", "pollution", "unep"], officialUrl: "https://www.unep.org/who-we-are/about-us", updatesUrl: "https://www.unep.org/news-and-stories", accent: "#8fbd78", logo: "/committee-logos/unep.png", logoAlt: "United Nations Environment Programme logo", feedGroups: ["un-news"] },
  { code: "ECOSOC", name: "Economic and Social Council", family: "Sustainable development", mandate: "Coordinates the economic, social and related work of the UN system and serves as a central platform for reflection, debate and policy innovation.", authority: "ECOSOC makes recommendations, coordinates specialised agencies, consults civil society and reviews progress on international development commitments.", focus: ["Sustainable Development Goals", "Financing for development", "Humanitarian coordination"], keywords: ["ecosoc", "economic and social", "sustainable development", "sdg", "financing for development"], officialUrl: "https://ecosoc.un.org/en/about-us", updatesUrl: "https://ecosoc.un.org/en/news", accent: "#d09b82", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "UN WOMEN", name: "United Nations Entity for Gender Equality", family: "Gender equality", mandate: "Supports global standards for gender equality and works with governments and civil society to make those standards effective for women and girls.", authority: "UN Women provides policy support, coordination, data and programmes. It advocates and assists implementation, but does not legislate for states or operate as a court.", focus: ["Women, peace and security", "Economic empowerment", "Ending violence against women"], keywords: ["un women", "gender equality", "women and girls", "women peace security"], officialUrl: "https://www.unwomen.org/en/about-us/about-un-women", updatesUrl: "https://www.unwomen.org/en/news-stories", accent: "#68afd2", logo: "/committee-logos/un-women.png", logoAlt: "UN Women logo", feedGroups: ["un-news"] },
  { code: "UNICEF", name: "United Nations Children's Fund", family: "Children and humanitarian action", mandate: "Protects the rights and wellbeing of children, especially those facing conflict, poverty, disease and exclusion.", authority: "UNICEF delivers programmes, humanitarian assistance, evidence and policy support with governments and partners. It does not pass binding international law.", focus: ["Child protection", "Education and health", "Humanitarian response"], keywords: ["unicef", "children", "child rights", "education", "child protection"], officialUrl: "https://www.unicef.org/about-unicef", updatesUrl: "https://www.unicef.org/press-releases", accent: "#47a9d7", logo: "/committee-logos/unicef.svg", logoAlt: "UNICEF logo", feedGroups: ["un-news"] },
  { code: "UNODC", name: "United Nations Office on Drugs and Crime", family: "Justice and rule of law", mandate: "Supports member states in making the world safer from drugs, organised crime, corruption and terrorism.", authority: "UNODC provides research, technical assistance and support for implementing international conventions. It is not a court or international police force.", focus: ["Organised crime", "Anti-corruption", "Crime prevention and justice"], keywords: ["unodc", "drugs and crime", "trafficking", "corruption", "organized crime"], officialUrl: "https://www.unodc.org/unodc/en/about-unodc/index.html", updatesUrl: "https://www.unodc.org/unodc/en/press/releases.html", accent: "#c493a7", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news", "un-geneva"] },
  { code: "LOK SABHA", name: "Lok Sabha — House of the People", family: "Indian parliamentary simulation", mandate: "Simulates the directly elected lower house of India’s Parliament, where representatives debate legislation, public policy and executive accountability.", authority: "In the real Parliament, the Lok Sabha passes legislation, controls public finance and holds the Council of Ministers accountable. A simulation follows the rules and agenda issued by its conference.", focus: ["Legislative debate", "Questions and accountability", "Public finance"], keywords: ["lok sabha", "parliament", "house of the people", "speaker", "legislation", "bill"], officialUrl: "https://sansad.in/ls", updatesUrl: "https://sansad.in/ls", accent: "#e3a06c", logo: "/committee-logos/india.svg", logoAlt: "State Emblem of India", feedGroups: ["india"], simulation: true },
  { code: "RAJYA SABHA", name: "Rajya Sabha — Council of States", family: "Indian parliamentary simulation", mandate: "Simulates the upper house of India’s Parliament, representing the states and union territories in national lawmaking and scrutiny.", authority: "The Rajya Sabha debates and passes legislation, reviews government policy and shares constitutional powers with the Lok Sabha, with specific differences for money bills and executive confidence.", focus: ["Federal representation", "Legislative scrutiny", "National policy"], keywords: ["rajya sabha", "council of states", "parliament", "chairman", "legislation", "bill"], officialUrl: "https://sansad.in/rs", updatesUrl: "https://sansad.in/rs", accent: "#d48d6d", logo: "/committee-logos/india.svg", logoAlt: "State Emblem of India", feedGroups: ["india"], simulation: true },
  { code: "AIPPM", name: "All India Political Parties Meet", family: "Indian political simulation", mandate: "A conference simulation in which participants represent Indian political leaders and negotiate a defined national policy question.", authority: "AIPPM is not a constitutional body and has no single official mandate. Its powers and procedure are created by each conference, so the issued background guide and rules remain controlling.", focus: ["Parliamentary negotiation", "Coalition-building", "Indian public policy"], keywords: ["parliament", "political parties", "cabinet", "election", "government policy", "legislation"], officialUrl: "https://sansad.in/", updatesUrl: "https://www.pib.gov.in/allRel.aspx?lang=1&reg=3", accent: "#e2a06f", logo: "/committee-logos/india.svg", logoAlt: "State Emblem of India", feedGroups: ["india"], simulation: true },
  { code: "HISTORIC", name: "Historic United Nations Simulation", family: "Historical diplomacy", mandate: "Recreates a United Nations body at a defined moment in history, asking delegates to decide with only the information available at that committee's freeze date.", authority: "This is a conference simulation, not a standing UN organ. The original body's powers still matter, but the issued freeze date, portfolio allocations and crisis rules define what delegates may know and do.", focus: ["Primary-source research", "Freeze-date discipline", "Counterfactual diplomacy"], keywords: ["united nations", "general assembly", "security council"], officialUrl: "https://digitallibrary.un.org/", updatesUrl: "https://news.un.org/en/", accent: "#b49acb", logo: "/committee-logos/un.svg", logoAlt: "United Nations emblem", feedGroups: ["un-news"], simulation: true },
];
