export type CommitteeProfile = {
  code: string;
  name: string;
  family: string;
  mandate: string;
  authority: string;
  focus: string[];
  keywords: string[];
  officialUrl: string;
  updatesUrl: string;
  accent: string;
  simulation?: boolean;
};

export const COMMITTEES: CommitteeProfile[] = [
  { code: "UNHRC", name: "United Nations Human Rights Council", family: "Human rights", mandate: "Promotes and protects human rights worldwide, addresses violations, and makes recommendations through resolutions, reviews and special procedures.", authority: "The Council can create fact-finding mechanisms, appoint independent experts, conduct the Universal Periodic Review and convene special sessions. It does not impose criminal sentences or deploy forces.", focus: ["Universal Periodic Review", "Special procedures", "Civil and political rights"], keywords: ["human rights", "rights council", "unhrc", "ohchr"], officialUrl: "https://www.ohchr.org/en/hr-bodies/hrc/about-council", updatesUrl: "https://www.ohchr.org/en/hr-bodies/hrc/news", accent: "#82b7d8" },
  { code: "UNSC", name: "United Nations Security Council", family: "Peace and security", mandate: "Carries primary responsibility for maintaining international peace and security under the United Nations Charter.", authority: "The Council may establish peace operations, impose sanctions, investigate disputes and, under the Charter, authorise collective action. Five permanent members hold veto power on substantive decisions.", focus: ["Conflict prevention", "Peace operations", "Sanctions and mandates"], keywords: ["security council", "unsc", "peacekeeping", "ceasefire"], officialUrl: "https://main.un.org/securitycouncil/en/content/what-security-council", updatesUrl: "https://main.un.org/securitycouncil/en", accent: "#d4b56d" },
  { code: "DISEC", name: "Disarmament and International Security Committee", family: "UN General Assembly First Committee", mandate: "Examines disarmament, global challenges and threats to peace that affect the international community.", authority: "DISEC develops General Assembly recommendations and norms through multilateral debate. Its resolutions are generally recommendatory rather than legally binding.", focus: ["Weapons governance", "Outer space security", "Confidence-building measures"], keywords: ["disarmament", "first committee", "weapons", "arms control"], officialUrl: "https://www.un.org/en/ga/first/", updatesUrl: "https://www.un.org/en/ga/first/", accent: "#9ba8cf" },
  { code: "WHO", name: "World Health Assembly", family: "Global health", mandate: "Sets the policies of the World Health Organization and brings member states together to decide global health priorities.", authority: "The Assembly appoints the Director-General, supervises financial policy and adopts conventions, regulations and recommendations within the WHO Constitution.", focus: ["Health emergencies", "Universal health coverage", "Antimicrobial resistance"], keywords: ["world health", "who", "health assembly", "public health"], officialUrl: "https://www.who.int/about/governance/world-health-assembly", updatesUrl: "https://www.who.int/news-room", accent: "#72b8aa" },
  { code: "UNEP", name: "United Nations Environment Programme", family: "Environment", mandate: "Provides leadership and encourages partnership in caring for the environment, helping nations improve quality of life without compromising future generations.", authority: "UNEP convenes states, produces authoritative science, supports environmental agreements and coordinates action; it relies on cooperation rather than enforcement powers.", focus: ["Climate action", "Nature and biodiversity", "Pollution and waste"], keywords: ["environment", "climate", "biodiversity", "pollution"], officialUrl: "https://www.unep.org/about-un-environment", updatesUrl: "https://www.unep.org/news-and-stories", accent: "#8fbd78" },
  { code: "ECOSOC", name: "Economic and Social Council", family: "Sustainable development", mandate: "Coordinates the economic, social and related work of the UN system and serves as a central platform for reflection, debate and policy innovation.", authority: "ECOSOC makes recommendations, coordinates specialised agencies, consults civil society and reviews progress on international development commitments.", focus: ["Sustainable Development Goals", "Financing for development", "Humanitarian coordination"], keywords: ["ecosoc", "economic and social", "sustainable development", "sdg"], officialUrl: "https://ecosoc.un.org/en/about-us", updatesUrl: "https://ecosoc.un.org/en/news", accent: "#d09b82" },
  { code: "UNODC", name: "United Nations Office on Drugs and Crime", family: "Justice and rule of law", mandate: "Supports member states in making the world safer from drugs, organised crime, corruption and terrorism.", authority: "UNODC provides research, technical assistance and support for implementing international conventions. It is not a court or international police force.", focus: ["Organised crime", "Anti-corruption", "Crime prevention and justice"], keywords: ["unodc", "drugs and crime", "trafficking", "corruption"], officialUrl: "https://www.unodc.org/unodc/en/about-unodc/index.html", updatesUrl: "https://www.unodc.org/unodc/en/press/releases.html", accent: "#c493a7" },
  { code: "AIPPM", name: "All India Political Parties Meet", family: "Indian political simulation", mandate: "A conference simulation in which participants represent Indian political leaders and negotiate a defined national policy question.", authority: "AIPPM is not a United Nations body and has no single official mandate. Its powers and procedure are created by each conference, so delegates should treat the issued background guide and rules as controlling.", focus: ["Parliamentary negotiation", "Coalition-building", "Indian public policy"], keywords: ["india", "parliament", "political"], officialUrl: "https://sansad.in/", updatesUrl: "https://pib.gov.in/", accent: "#e2a06f", simulation: true },
  { code: "HISTORIC", name: "Historic United Nations Simulation", family: "Historical diplomacy", mandate: "Recreates a United Nations body at a defined moment in history, asking delegates to decide with only the information available at that committee's freeze date.", authority: "This is a conference simulation, not a standing UN organ. The original body's powers still matter, but the issued freeze date, portfolio allocations and crisis rules define what delegates may know and do.", focus: ["Primary-source research", "Freeze-date discipline", "Counterfactual diplomacy"], keywords: ["united nations", "general assembly", "security council"], officialUrl: "https://digitallibrary.un.org/", updatesUrl: "https://news.un.org/en/", accent: "#b49acb", simulation: true },
];
